[
    {
        "doNumber": "F048033362",
        "originPort": "TWKHH",
        "destinationPort": "USLAX",
        "shipmentType": "IMPORT",
        "containerNumber": "TGBU8864817",
        "customerName": "Expeditors",
        "bcoName": "John Deere",
        "pickupDateTime": "12/21/2045 23:00",
        "deliveryDateTime": "12/21/2045 23:00",
        "emptyPickupName": "NORFOLK SOUTHERN RAILROAD",
        "emptyPickupAddress1": "7540 S Western Ave",
        "emptyPickupAddress2": "",
        "emptyPickupCity": "Chicago",
        "emptyPickupState": "IL",
        "emptyPickupPostalCode": "60620",
        "emptyPickupCountry": "US",
        "originName": "NORFOLK SOUTHERN RAILROAD",
        "originAddress1": "7540 S Western Ave",
        "originAddress2": "",
        "originCity": "Chicago",
        "originState": "IL",
        "originPostalCode": "60620",
        "originCountry": "US",
        "destName": "TRAPAC",
        "destAddress1": "9834 NEW BERLIN ROAD",
        "destAddress2": "",
        "destCity": "Jacksonville",
        "destState": "FL",
        "destPostalCode": "32226",
        "destCountry": "US",
        "billOfLadingNum": "COSU6329980010",
        "bookingNumber": "COSU6329980010",
        "invoiceRefNum": "COSU6329980010",
        "commodityClass": "FAK",
        "commodityGoodsNum": "4611110",
        "freightDescription": "FAK",
        "isHazmat": "N",
        "containerType": "40ST",
        "sealNumber": "20786505",
        "packages": "900",
        "packageUOM": "Pieces",
        "cutoffDate": "12/21/2045 23:00",
        "docCutoffDate": "12/21/2045 23:00",
        "grossWeight": "2104",
        "netWeight": "2104",
        "weightUOM": "KG",
        "volume": "68",
        "volumeUOM": "MTQ",
        "ocaScac": "SUDU",
        "ocaName": "Bear Cartage",
        "vesselName": "SEATTLE C",
        "voyageNumber": "0FT8ZS1MA"
    }
]