[
    {
        "doNumber": "VALR230518484235",
        "doStatus": "DRAFT",
        "doType": "IMPORT",
        "billOfLading": "COSU6329980010",
        "booking": "COSU6329980010",
        "originPort": "ITSLONGB",
        "destinationPort": "USPAPHILA",
        "invoiceReferenceNumber": "COSU6329980010",
        "customerCode": "EXPD",
        "customerName": "Expeditors",
        "bcoName": "John Deere",
        "oceanCarrier": "Bear Cartage",
        "voyage": "0FT8ZS1MA",
        "vessel": "SEATTLE C",
        "standardCarrierAlphaCode": "BCRG-CHI",
        "comments": null,
        "shipments": [],
        "cargo": {
            "quantity": 900,
            "quantityUOM": "PC",
            "commodityGoodsNumber": "4611110",
            "freightDescription": "FAK",
            "commodityClass": "FAK",
            "commodityComments": null,
            "isHazmat": false,
            "grossWeight": 2104.0,
            "grossWeightUOM": "KG",
            "tareWeight": 8400.0,
            "tareWeightUOM": "KG",
            "netWeight": 2104.0,
            "netWeightUOM": "KG",
            "grossVolume": 68.0,
            "grossVolumeUOM": "MTQ",
            "temperature": null,
            "temperatureUOM": null,
            "isShipmentOverweight": false,
            "packageType": "TOTAL_LOAD"
        },
        "container": {
            "number": "TGBU8864817",
            "equipmentSizeType": "40ST",
            "seal": "20786505",
            "isStackable": false,
            "isLoaded": "Y"
        },
        "stops": [
            {
                "doId": "VALR230518484235",
                "stopType": "PICKUP",
                "stopNumber": 0,
                "locationName": "NORFOLK SOUTHERN RAILROAD",
                "locationId": 17008,
                "locationCode": "unknown0724",
                "locationType": "unknown0724",
                "locationAddress1": "7540 S Western Ave",
                "locationAddress2": "",
                "city": "Chicago",
                "state": "IL",
                "country": "US",
                "postalCode": null
            },
            {
                "doId": "VALR230518484235",
                "stopType": "LIVELOAD",
                "stopNumber": 1,
                "locationName": "NORFOLK SOUTHERN RAILROAD",
                "locationId": 17008,
                "locationCode": "unknown0724",
                "locationType": "unknown0724",
                "locationAddress1": "7540 S Western Ave",
                "locationAddress2": "",
                "city": "Chicago",
                "state": "IL",
                "country": "US",
                "postalCode": null
            },
            {
                "doId": "VALR230518484235",
                "stopType": "DELIVERY",
                "stopNumber": 2,
                "locationName": "TRAPAC",
                "locationId": 17007,
                "locationCode": "unknown7463",
                "locationType": "unknown7463",
                "locationAddress1": "9834 NEW BERLIN ROAD",
                "locationAddress2": null,
                "city": "Jacksonville",
                "state": "FL",
                "country": "US",
                "postalCode": null
            }
        ],
        "deliverySchedule": {
            "cutOffDate": null,
            "documentationCutOffDate": null,
            "lastFreeDate": null,
            "plannedPickup": "12-21-2045",
            "plannedVesselDeparture": null,
            "scheduledDeliveryDate": "12-21-2045",
            "returnDeliveryOrder": null,
            "bondedMove": false,
            "fumigationReqdAt": "None"
        },
        "customAttributes": null,
        "doEvents": [],
        "deliveryOrderCustomerReferenceNumber": "F048033362"
    }
]